name: mocha-test
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base>=4.3
  - r-devtools
  - r-testthat>=3.0.0
  - r-remotes
  - r-biocmanager
  - r-dplyr
  - r-data.table
  - r-stringr
  - r-magrittr
  - r-ggplot2
  - r-matrixstats
  - r-scales
  - r-tidyr
  - r-pbapply
  - bioconductor-qvalue
  - r-lme4
  - r-lmertest
  - r-glmmtmb
  - r-matrix
  - r-irlba
  - r-purrr
  - r-withr
  - r-waldo
  - r-assertthat
  - r-cowplot
  - r-ggrepel
  - r-ggridges
  - r-zoo
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-multiassayexperiment
  - bioconductor-raggedexperiment
  - bioconductor-genomicfeatures
  - bioconductor-genomeinfodb
  - bioconductor-biocgenerics
  - bioconductor-annotationdbi
  - bioconductor-bsgenome
  - bioconductor-txdb.hsapiens.ucsc.hg38.refgene
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-org.hs.eg.db
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-plyranges
